apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oc-lab-pvc
spec:
  storageClassName: skills-network-learner
  resources:
    requests:
      storage:  1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce